--- #YAML:1.0
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: 'Build version '
license: perl
name: Acme-Hello
recommends:
  Locale::Maketext: 0.20
  Locale::Maketext::Lexicon: 0.08
requires:
  perl: 5.005
version: 0.01
